-- Add detailed measurements and fields to customization_requests table
ALTER TABLE `customization_requests` 
ADD COLUMN IF NOT EXISTS `neck_circumference` DECIMAL(10,2) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS `inseam_length` DECIMAL(10,2) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS `arm_circumference` DECIMAL(10,2) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS `fabric_weight` VARCHAR(50) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS `budget_min` DECIMAL(10,2) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS `budget_max` DECIMAL(10,2) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS `quantity` INT DEFAULT 1,
ADD COLUMN IF NOT EXISTS `deadline` DATE DEFAULT NULL,
ADD COLUMN IF NOT EXISTS `reference_image_2` VARCHAR(255) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS `reference_image_3` VARCHAR(255) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS `garment_purpose` VARCHAR(100) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS `occasion` VARCHAR(200) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS `payment_method` VARCHAR(50) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS `delivery_mode` VARCHAR(50) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS `delivery_address` TEXT DEFAULT NULL,
ADD COLUMN IF NOT EXISTS `cancellation_reason` TEXT DEFAULT NULL;
